
This guide walks you through the process of creating an application that accesses Pivotal GemFire data through a
link:/guides/gs/rest-hateoas[hypermedia-based] link:/understanding/REST[REST-ful frontend].

== What you'll build

You'll build a _Spring_ Web application that let's you create and retrieve `Person` objects stored in the
http://pivotal.io/big-data/pivotal-gemfire[Pivotal GemFire] In-Memory Data Grid using Spring Data REST.
Spring Data REST takes the features of http://projects.spring.io/spring-hateoas[Spring HATEOAS]
and http://projects.spring.io/spring-data-gemfire[Spring Data for Pivotal GemFire] and combines them together
automatically.

TIP: For more general knowledge of Pivotal GemFire concepts and accessing data from Pivotal GemFire, read through the guide,
https://spring.io/guides/gs/accessing-data-gemfire/[Accessing Data with Pivotal GemFire].

== Create a domain object

Create a new domain object to present a person.

`src/main/java/hello/Person.java`

The `Person` has a first and last name. Pivotal GemFire domain objects need an id, so an `AtomicLong` is being used
to increment with each `Person` object creation.

== Create a Person Repository

Next, you need to create a simple _Repository_ to persist/access `Person` objects stored in Pivotal GemFire.

`src/main/java/hello/PersonRepository.java`

This _Repository_ is an interface and will allow you to perform various data access operations (e.g. basic CRUD
and simple queries) involving `Person` objects. It gets these operations by extending `CrudRepository`.

At runtime, _Spring Data for Pivotal GemFire_ will create an implementation of this interface automatically.
Then, Spring Data REST will use the
http://docs.spring.io/spring-data/rest/docs/{spring_data_rest}/api/org/springframework/data/rest/core/annotation/RepositoryRestResource.html[@RepositoryRestResource]
annotation to direct Spring MVC to create REST-ful endpoints at `/people`.

NOTE: `@RepositoryRestResource` is not required for a _Repository_ to be exported. It is only used to change the export
details, such as using `/people` instead of the default value of `/persons`.

Here you have also defined a custom query to retrieve a list of `Person` objects based on `lastName`. You'll see how to
invoke it further down in this guide.

== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to
an external application server, the simpler approach demonstrated below creates a standalone application. You package
everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use _Spring's_
support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying
to an external servlet container.

`src/main/java/hello/Application.java`

The `@EnableGemfireRepositories` annotation activates _Spring Data for Pivotal GemFire_ _Repositories_.
_Spring Data for Pivotal GemFire_ will create a concrete implementation of the `PersonRepository` interface
and configure it to talk to an embedded instance of Pivotal GemFire.

== Build an executable JAR

```bash
./mvnw spring-boot:run

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

./mvnw clean package
```

== Test the application

Now that the application is running, you can test it. You can use any REST client you wish. The following examples uses
the *nix tool `curl`.

First you want to see the top level service.

```
$ curl http://localhost:8080
{
  "_links" : {
    "people" : {
      "href" : "http://localhost:8080/people"
    }
  }
}
```

Here you get your first glimpse of what this server has to offer. There is a **people** link located at
http://localhost:8080/people. _Spring Data for Pivotal GemFire_ doesn't support pagination like the other
Spring Data REST guides so there are no extra navigational links.

NOTE: Spring Data REST uses the http://stateless.co/hal_specification.html[HAL format] for JSON output. It is flexible
and offers a convenient way to supply links adjacent to the data that is served.

```
$ curl http://localhost:8080/people
{
  "_links" : {
    "search" : {
      "href" : "http://localhost:8080/people/search"
    }
  }
}
```

Time to create a new `Person`!

```
$ curl -i -X POST -H "Content-Type:application/json" -d '{  "firstName" : "Frodo",  "lastName" : "Baggins" }' http://localhost:8080/people
HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
Location: http://localhost:8080/people/1
Content-Length: 0
Date: Wed, 05 Mar 2014 20:16:11 GMT
```

- `-i` ensures you can see the response message including the headers. The URI of the newly created `Person` is shown
- `-X POST` issues a `POST` HTTP request to create a new entry
- `-H "Content-Type:application/json"` sets the content-type so the application knows the payload contains a JSON object
- `-d '{  "firstName" : "Frodo",  "lastName" : "Baggins" }'` is the data being sent

NOTE: Notice how the previous `POST` operation includes a `Location` header. This contains the URI of
the newly created resource. Spring Data REST also has two methods on `RepositoryRestConfiguration.setReturnBodyOnCreate(…)`
and `setReturnBodyOnCreate(…)` which you can use to configure the framework to immediately return the representation
of the resource just created.

From this you can query for all people:

```
$ curl http://localhost:8080/people
{
  "_links" : {
    "search" : {
      "href" : "http://localhost:8080/people/search"
    }
  },
  "_embedded" : {
    "persons" : [ {
      "firstName" : "Frodo",
      "lastName" : "Baggins",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/people/1"
        }
      }
    } ]
  }
}
```

The **people** collection resource contains a list with Frodo. Notice how it includes a **self** link. Spring Data REST
also uses http://www.atteo.org/2011/12/12/Evo-Inflector.html[Evo Inflector] to pluralize the name of the entity
for groupings.

You can query directly for the individual record:

```
$ curl http://localhost:8080/people/1
{
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/people/1"
    }
  }
}
```

NOTE: This might appear to be purely web based, but behind the scenes, it is talking to
an embedded Pivotal GemFire database.

In this guide, there is only one domain object. With a more complex system where domain objects are related
to each other, Spring Data REST will render additional links to help navigate to connected records.

Find all the custom queries:

```
$ curl http://localhost:8080/people/search
{
  "_links" : {
    "findByLastName" : {
      "href" : "http://localhost:8080/people/search/findByLastName{?name}",
      "templated" : true
    }
  }
}
```

You can see the URL for the query including the HTTP query parameter `name`. If you'll notice, this matches
the `@Param("name")` annotation embedded in the interface.

To use the `findByLastName` query, do this:

```
$ curl http://localhost:8080/people/search/findByLastName?name=Baggins
{
  "_embedded" : {
    "persons" : [ {
      "firstName" : "Frodo",
      "lastName" : "Baggins",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/people/1"
        }
      }
    } ]
  }
}
```

Because you defined it to return `List<Person>` in the code, it will return all of the results. If you had defined it
to only return `Person`, it would pick one of the `Person` objects to return. Since this can be unpredictable,
you probably don't want to do that for queries that can return multiple entries.

You can also issue `PUT`, `PATCH`, and `DELETE` REST calls to either replace, update, or delete existing records.

```
$ curl -X PUT -H "Content-Type:application/json" -d '{ "firstName": "Bilbo", "lastName": "Baggins" }' http://localhost:8080/people/1
$ curl http://localhost:8080/people/1
{
  "firstName" : "Bilbo",
  "lastName" : "Baggins",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/people/1"
    }
  }
}
```

```
$ curl -X PATCH -H "Content-Type:application/json" -d '{ "firstName": "Bilbo Jr." }' http://localhost:8080/people/1
$ curl http://localhost:8080/people/1
{
  "firstName" : "Bilbo Jr.",
  "lastName" : "Baggins",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/people/1"
    }
  }
}
```

NOTE: `PUT` replaces an entire record. Fields not supplied will be replaced with `null`. `PATCH` can be used to
update a subset of items.

You can delete records:

```
$ curl -X DELETE http://localhost:8080/people/1
$ curl http://localhost:8080/people
{
  "_links" : {
    "search" : {
      "href" : "http://localhost:8080/people/search"
    }
  }
}
```

A very convenient aspect of this link:/understanding/HATEOAS[hypermedia-driven interface] is how you can discover
all the REST-ful endpoints using `curl` (or whatever REST client you are using). There is no need to exchange
a formal contract or interface document with your customers.
