
This guide walks you through the process of creating a "Hello, Spring!" RESTful web
service with Spring WebFlux (new as of version 5) and then consumes that service with a
WebClient (also new as of version 5).

NOTE: This guide shows the functional way of using Spring WebFlux. You can also
https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-controller[use annotations with WebFlux].

== What You'll Build

You’ll build a RESTful web service with Spring Webflux and a WebClient consumer of that
service. You'll be able to see output in both System.out and at:

[source]
http://localhost:8080/hello

== Create a WebFlux Handler

In the Spring Reactive approach, we use a handler to handle the request and create a
response, as shown in the following example: `src/main/java/hello/GreetingHandler.java`.

This simple reactive class always returns "Hello, Spring!" It could return many other
things, including a stream of items from a database, a stream of items that were
generated by calculations, and so on. Note the reactive code: a `Mono` object that holds
a `ServerResponse` body.

== Create a Router

In this application, we use a router to handle the only route we expose ("/hello"), as
shown in the following example: `src/main/java/hello/GreetingRouter.java`.

The router listens for traffic on the `/hello` path and returns the value provided by our
reactive handler class.

== Create a WebClient

The Spring MVC RestTemplate class is, by nature, blocking. Consequently, we don't
want to use it in a reactive application. For reactive applications, Spring offers the
WebClient class, which is non-blocking. We'll use a WebClient implementation
to consume our RESTful service: `src/main/java/hello/GreetingWebClient.java`.

The WebClient uses reactive features, in the form of a Mono to hold the content of the URI
we specify and a function (in the `getResult` method) to turn that content into a string.
If we had different requirements, we might turn it into something other than a string.
Since we're going to put the result into System.out, a string will do here.

TIP: WebClient can be used to communicate with non-reactive, blocking services, too.

== Make the Application Executable

Although it is possible to package this service as a traditional
link:/understanding/WAR[WAR] file for deployment to an external application server,
the simpler approach demonstrated below creates a standalone application. You package
everything in a single, executable JAR file, driven by a good old Java `main()` method.
Along the way, you use Reactive Spring's support for embedding the Netty server as the
HTTP runtime, instead of deploying to an external instance.

See the `src/main/java/hello/Application.java`.

== Build an executable JAR

If you use Gradle, you can run the application by using `./gradlew bootRun`. Alternatively, you can build the JAR file by using `./gradlew build` and then run the JAR file.

If you use Maven, you can run the application by using `./mvnw spring-boot:run`. Alternatively, you can build the JAR file with `./mvnw clean package` and then run the JAR file, as follows:

[source]
java -jar build/libs/gs-reactive-rest-service-0.1.0.jar

Logging output is displayed. The service should be up and running within a few seconds.

Once the service has started, you'll see a line that reads:

`>> result = Hello, Spring!`

That line comes from the reactive content being consumed by the WebClient. Naturally,
you can find something more interesting to do with your output than put it in System.out.

== Test the Application

Now that the application is running, you can test it. To start with, you can open a
browser and go to `http://localhost:8080/hello` and see, "Hello, Spring!" For this guide,
we also created a test class to get you started on testing with the WebTestClient class.

See the `src/test/java/hello/GreetingRouterTest.java`.
