
This guide walks you through the process of consuming a SOAP-based web service with
Spring.

== What You Will Build

You will build a client that fetches country data data from a remote, WSDL-based web
service by using http://en.wikipedia.org/wiki/SOAP[SOAP].
You can find out more about the country service and run the service yourself by following
https://spring.io/guides/gs/producing-web-service/[this guide].

The service provides country data. You will be able to query data about a country based on its name.

== Run the Target Web Service Locally

Follow the steps in the
https://spring.io/guides/gs/producing-web-service/[companion guide] or clone the
https://github.com/spring-guides/gs-producing-web-service[repository] and run the service
(for example, by using `mvn spring-boot:run`) from its `complete` directory. You can
verify that it works by visiting `http://localhost:8080/ws/countries.wsdl` in your
browser. If you don't do this you will see a confusing exception in your build later from the JAXB tooling.

[[scratch]]

== Modify the Build Files

The build files created by the Spring Initializr need quite a bit of work for this guide.
Also, the modifications to `pom.xml` (for Maven) and `build.gradle` (for Gradle) differ
substantially.

=== Maven

For Maven, you need to add a dependency, a profile, and a WSDL generation plugin.

The following listing shows the dependency you need to add in Maven:

====
[source,xml,indent=0]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web-services</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
		</exclusion>
	</exclusions>
</dependency>
----
====

The following listing shows the profile you need to add in Maven if you want it to work with Java 11:

====
[source,xml,indent=0]
----
<profiles>
	<profile>
		<id>java11</id>
		<activation>
			<jdk>[11,)</jdk>
		</activation>

		<dependencies>
			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-runtime</artifactId>
			</dependency>
		</dependencies>
	</profile>
</profiles>
----
====

The <<initial>> section describes the WSDL generation plugin.

=== Gradle

For Gradle, you need to add a dependency, a configuration, a `bootJar` section, and a WSDL
generation plugin.

The following listing shows the dependency you need to add in Gradle:

====
[source,xml,indent=0]
----
implementation ('org.springframework.boot:spring-boot-starter-web-services') {
	exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
}
implementation 'org.springframework.ws:spring-ws-core'
// For Java 11:
implementation 'org.glassfish.jaxb:jaxb-runtime'
compile(files(genJaxb.classesDir).builtBy(genJaxb))

jaxb "com.sun.xml.bind:jaxb-xjc:2.1.7"
----
====

Note the exclusion of Tomcat. If Tomcat is allowed to run in this build, you get a port
collision with the Tomcat instance that provides the country data.

The following listing shows the `bootJar` section you need to add in Gradle:

====
[source,xml,indent=0]
----
bootJar {
	baseName = 'gs-consuming-web-service'
	version =  '0.0.1'
}
----
====

The <<initial>> section describes the WSDL generation plugin.

[[initial]]
== Generate Domain Objects Based on a WSDL

The interface to a SOAP web service is captured in
http://en.wikipedia.org/wiki/Web_Services_Description_Language[WSDL]. JAXB provides a way
to generate Java classes from WSDL (or rather, the XSD contained in the `<Types/>` section
of the WSDL). You can find the WSDL for the country service at
`http://localhost:8080/ws/countries.wsdl`.

To generate Java classes from the WSDL in Maven, you need the following plugin setup:

====
[source,xml,indent=0]
----
<plugin>
		<groupId>org.jvnet.jaxb2.maven2</groupId>
		<artifactId>maven-jaxb2-plugin</artifactId>
		<version>0.14.0</version>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<schemaLanguage>WSDL</schemaLanguage>
			<generatePackage>com.example.consumingwebservice.wsdl</generatePackage>
			<schemas>
				<schema>
					<url>http://localhost:8080/ws/countries.wsdl</url>
				</schema>
			</schemas>
		</configuration>
</plugin>
----
====

This setup will generate classes for the WSDL found at the specified URL, putting those
classes in the `com.example.consumingwebservice.wsdl` package. To generate that code run `./mvnw compile`
and then look in `target/generated-sources` if you want to check that it worked.

To do the same with Gradle, you will need the following in your build file:

====
[source,java,tabsize=2,indent=0]
----
task genJaxb {
  ext.sourcesDir = "${buildDir}/generated-sources/jaxb"
  ext.classesDir = "${buildDir}/classes/jaxb"
  ext.schema = "http://localhost:8080/ws/countries.wsdl"

  outputs.dir classesDir

  doLast() {
    project.ant {
      taskdef name: "xjc", classname: "com.sun.tools.xjc.XJCTask",
          classpath: configurations.jaxb.asPath
      mkdir(dir: sourcesDir)
      mkdir(dir: classesDir)

        xjc(destdir: sourcesDir, schema: schema,
            package: "com.example.consumingwebservice.wsdl") {
            arg(value: "-wsdl")
          produces(dir: sourcesDir, includes: "**/*.java")
        }

        javac(destdir: classesDir, source: 1.8, target: 1.8, debug: true,
            debugLevel: "lines,vars,source",
            classpath: configurations.jaxb.asPath) {
          src(path: sourcesDir)
          include(name: "**/*.java")
          include(name: "*.java")
          }

        copy(todir: classesDir) {
            fileset(dir: sourcesDir, erroronmissingdir: false) {
            exclude(name: "**/*.java")
        }
      }
    }
  }
}
----
====

As Gradle does not (yet) have a JAXB plugin, it involves an Ant task, which makes it a bit
more complex than in Maven. To generate that code run `./gradlew compileJava`
and then look in `build/generated-sources` if you want to check that it worked.

In both cases, the JAXB domain object generation process has been wired into the build
tool's lifecycle, so you need not run any extra steps once you have a successful build.

== Create a Country Service Client

To create a web service client, you have to extend the
http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/client/core/support/WebServiceGatewaySupport.html[`WebServiceGatewaySupport`]
class and code your operations, as the following example (from
`src/main/java/com/example/consumingwebservice/CountryClient.java`).

The client contains one method (`getCountry`) that does the actual SOAP exchange.

In this method, both the `GetCountryRequest` and the `GetCountryResponse` classes are
derived from the WSDL and were generated in the JAXB generation process (described in
<<initial>>). It creates the `GetCountryRequest` request object and sets it up with the
`country` parameter (the name of the country). After printing out the country name, it
uses the
http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/client/core/WebServiceTemplate.html[`WebServiceTemplate`]
supplied by the `WebServiceGatewaySupport` base class to do the actual SOAP exchange. It
passes the `GetCountryRequest` request object (as well as a `SoapActionCallback` to pass
on a http://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528[SOAPAction] header with
the request) as the WSDL described that it needed this header in the `<soap:operation/>`
elements. It casts the response into a `GetCountryResponse` object, which is then
returned.

== Configuring Web Service Components

Spring WS uses Spring Framework's OXM module, which has the `Jaxb2Marshaller` to serialize
and deserialize XML requests, as the following example (from
`src/main/java/com/example/consumingwebservice/CountryConfiguration.java`).

The `marshaller` is pointed at the collection of generated domain objects and will use
them to both serialize and deserialize between XML and POJOs.

编组器指向生成的域对象的集合，并将使用它们在XML和POJO之间进行序列化和反序列化。

The `countryClient` is created and configured with the URI of the country service shown
earlier. It is also configured to use the JAXB marshaller.

== Run the Application

This application is packaged up to run from the console and retrieve the data for a given
country name, as the following listing (from
`src/main/java/com/example/consumingwebservice/ConsumingWebServiceApplication.java`).

The `main()` method defers to the
http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html[`SpringApplication`] helper class, providing
`CountryConfiguration.class` as an argument to its `run()` method. This tells Spring to
read the annotation metadata from `CountryConfiguration` and to manage it as a component
in the Spring application context.

NOTE: This application is hard-coded to look up 'Spain'. Later in this guide, you will see
how to enter a different symbol without editing the code.

Build an executable JAR

You can run the application from the command line with Gradle or Maven. You can also build a single executable JAR file that contains all the necessary dependencies, classes, and resources and run that. Building an executable jar makes it easy to ship, version, and deploy the service as an application throughout the development lifecycle, across different environments, and so forth.

If you use Gradle, you can run the application by using `./gradlew bootRun`. Alternatively, you can build the JAR file by using ./gradlew build and then run the JAR file, as follows:

====
[source,bash]
----
./gradlew build

java -jar build/libs/gs-consuming-web-service-0.1.0.jar
----
====

If you use Maven, you can run the application by using `./mvnw spring-boot:run`. Alternatively, you can build the JAR file with ./mvnw clean package and then run the JAR file, as follows:

====
[source,bash]
----
./mvnw clean package

java -jar target/gs-consuming-web-service-0.1.0.jar
----
====

Logging output is displayed. The service should be up and running within a few seconds.

The following listing shows the initial response:

====
[source]
----
Requesting country data for Spain

<getCountryRequest><name>Spain</name>...</getCountryRequest>
----
====

You can plug in a different country by running the following command:

====
[source,bash]
----
java -jar build/libs/gs-consuming-web-service-0.1.0.jar Poland
----
====

Then the response changes to the following:

====
[source]
----
Requesting location for Poland

<getCountryRequest><name>Poland</name>...</getCountryRequest>
----
====
