
This guide walks you through the process of creating a SOAP-based web service server with
Spring.

== What You Will build

You will build a server that exposes data from various European countries by using a
WSDL-based SOAP web service.

NOTE: To simplify the example, you will use hardcoded data for the United Kingdom, Spain,
and Poland.

== Add the Spring-WS dependency

The project needs to include `spring-ws-core` and `wsdl4j` as dependencies in your build
file.

The following example shows the changes you need to make to the `pom.xml` file if you use
Maven:

====
[source,xml,indent=0]
----
<dependency>
	<groupId>wsdl4j</groupId>
	<artifactId>wsdl4j</artifactId>
</dependency>
----
====

The following example shows the changes you need to make to the `build.gradle` file if
you use Gradle:

====
[source,java,indent=0]
----
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-web-services'
	implementation 'wsdl4j:wsdl4j:1.6.1'
	jaxb("org.glassfish.jaxb:jaxb-xjc:2.2.11")
	compile(files(genJaxb.classesDir).builtBy(genJaxb))
  testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}
----
====

== Create an XML Schema to Define the Domain

The web service domain is defined in an XML schema file (XSD) that Spring-WS will
automatically export as a WSDL.

Create an XSD file with operations to return a country's `name`, `population`, `capital`,
and `currency`. The following listing (from `src/main/resources/countries.xsd`) .

== Generate Domain Classes Based on an XML Schema

The next step is to generate Java classes from the XSD file. The right approach is to do
this automatically during build time by using a Maven or Gradle plugin.

The following listing shows the necessary plugin configuration for Maven:

====
[source,xml,indent=0]
----
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>jaxb2-maven-plugin</artifactId>
	<version>2.5.0</version>
	<executions>
		<execution>
			<id>xjc</id>
			<goals>
				<goal>xjc</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<sources>
			<source>${project.basedir}/src/main/resources/countries.xsd</source>
		</sources>
	</configuration>
</plugin>
----
====

Generated classes are placed in the `target/generated-sources/jaxb/` directory.

To do the same with Gradle, you first need to configure JAXB in your build file, as the
following listing shows:

====
[source,java,indent=0]
----
configurations {
    jaxb
}

bootJar {
    baseName = 'gs-producing-web-service'
    version =  '0.1.0'
}
----
====

NOTE: The build files have `tag` and `end` comments. These tags make it easier to extract
bits of it into this guide for a more detailed explanation. You do not need these comments
in your own build file.

The next step is to add the `genJaxb` task, which Gradle usesto generate Java classes. The
following listing shows the necesary addition:

====
[source,java,indent=0]
----
task genJaxb {
    ext.sourcesDir = "${buildDir}/generated-sources/jaxb"
    ext.classesDir = "${buildDir}/classes/jaxb"
    ext.schema = "src/main/resources/countries.xsd"

    outputs.dir classesDir

    doLast() {
        project.ant {
            taskdef name: "xjc", classname: "com.sun.tools.xjc.XJCTask",
                    classpath: configurations.jaxb.asPath
            mkdir(dir: sourcesDir)
            mkdir(dir: classesDir)

            xjc(destdir: sourcesDir, schema: schema) {
                arg(value: "-wsdl")
                produces(dir: sourcesDir, includes: "**/*.java")
            }

            javac(destdir: classesDir, source: 1.6, target: 1.6, debug: true,
                    debugLevel: "lines,vars,source", includeantruntime: false,
                    classpath: configurations.jaxb.asPath) {
                src(path: sourcesDir)
                include(name: "**/*.java")
                include(name: "*.java")
            }

            copy(todir: classesDir) {
                fileset(dir: sourcesDir, erroronmissingdir: false) {
                    exclude(name: "**/*.java")
                }
            }
        }
    }
}
----
====

Because Gradle does not have a JAXB plugin (yet), it involves an Ant task, which makes it
a bit more complex than in Maven.

In both cases, the JAXB domain object generation process has been wired into the build
tool’s lifecycle, so there are no extra steps to run.

== Create Country Repository

In order to provide data to the web service, create a country repository. In this guide,
you create a dummy country repository implementation with hardcoded data. The following
listing (from `src/main/java/com/example/producingwebservice/CountryRepository.java`).

== Create Country Service Endpoint

To create a service endpoint, you need only a POJO with a few Spring WS annotations to
handle the incoming SOAP requests. The following listing (from
`src/main/java/com/example/producingwebservice/CountryEndpoint.java`).

The {Endpoint}[`@Endpoint`] annotation registers the class with Spring WS as a potential
candidate for processing incoming SOAP messages.

The {PayloadRoot}[`@PayloadRoot`] annotation is then used by Spring WS to pick the handler
method, based on the message's `namespace` and `localPart`.

The {RequestPayload}[`@RequestPayload`] annotation indicates that the incoming message
will be mapped to the method's `request` parameter.

The {ResponsePayload}[`@ResponsePayload`] annotation makes Spring WS map the returned
value to the response payload.

NOTE: In all of these chunks of code, the `io.spring.guides` classes will report
compile-time errors in your IDE unless you have run the task to generate the domain
classes based on the WSDL.

== Configure Web Service Beans

Create a new class with Spring WS-related beans configuration, as the following listing
(from `src/main/java/com/example/producingwebservice/WebServiceConfig.java`) .

* Spring WS uses a different servlet type for handling SOAP messages:
{MessageDispatcherServlet}[`MessageDispatcherServlet`]. It is important to inject and set
{ApplicationContext}[`ApplicationContext`] to
{MessageDispatcherServlet}[`MessageDispatcherServlet`]. Without that, Spring WS will not
automatically detect Spring beans.
* Naming this bean `messageDispatcherServlet` does not replace Spring Boot's
http://docs.spring.io/spring-boot/docs/{spring_boot_version}/reference/htmlsingle/#howto-switch-off-the-spring-mvc-dispatcherservlet[default `DispatcherServlet` bean].
* {DefaultMethodEndpointAdapter}[`DefaultMethodEndpointAdapter`] configures the
annotation-driven Spring WS programming model. This makes it possible to use the various
annotations, such as {Endpoint}[`@Endpoint`] (mentioned earlier).
* {DefaultWsdl11Definition}[`DefaultWsdl11Definition`] exposes a standard WSDL 1.1 by
using {XsdSchema}[`XsdSchema`]

IMPORTANT: You need to specify bean names for
{MessageDispatcherServlet}[`MessageDispatcherServlet`] and
{DefaultWsdl11Definition}[`DefaultWsdl11Definition`]. Bean names determine the URL under
which the web service and the generated WSDL file are available. In this case, the WSDL
will be available under `http://<host>:<port>/ws/countries.wsdl`.

This configuration also uses the WSDL location servlet transformation:
`servlet.setTransformWsdlLocations(true)`. If you visit
http://localhost:8080/ws/countries.wsdl, the `soap:address` will have the proper address.
If you instead
visit the WSDL from the public facing IP address assigned to your machine, you will see
that address instead.

== Test the Application

Because in the VSCode, the spring project can't build so we use command line to run the project.

If you use Gradle, run the following command in a terminal window (in the project directory):
====
[source,bash]
----
./gradlew bootRun
----
====

If you use Maven, run the following command in a terminal window (in the complete directory):
====
[source,bash]
----
./mvnw spring-boot:run
----
====

Now that the application is running, you can test it. Create a file called `request.xml`
that contains the SOAP request.

The are a few options when it comes to testing the SOAP interface. You can use something
similar to http://www.soapui.org[SoapUI] or use command-line tools if you are on a
*nix/Mac system. The following example uses curl from the command line:

====
[source,bash]
----
# Use data from file
curl --header "content-type: text/xml" -d @request.xml http://localhost:8080/ws
----

[source,bash]
----
# Use inline XML data
curl <<-EOF -fsSL -H "content-type: text/xml" -d @- http://localhost:8080/ws \
  > target/response.xml && xmllint --format target/response.xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                                  xmlns:gs="http://spring.io/guides/gs-producing-web-service">
   <soapenv:Header/>
   <soapenv:Body>
      <gs:getCountryRequest>
         <gs:name>Spain</gs:name>
      </gs:getCountryRequest>
   </soapenv:Body>
</soapenv:Envelope>

EOF
----
====

As a result, you should see the following response:

====
[source,xml]
----
<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header/>
  <SOAP-ENV:Body>
    <ns2:getCountryResponse xmlns:ns2="http://spring.io/guides/gs-producing-web-service">
      <ns2:country>
        <ns2:name>Spain</ns2:name>
        <ns2:population>46704314</ns2:population>
        <ns2:capital>Madrid</ns2:capital>
        <ns2:currency>EUR</ns2:currency>
      </ns2:country>
    </ns2:getCountryResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
----
====

NOTE: Odds are that the output will be a compact XML document instead of the nicely formatted one shown above. If you have xmllib2 installed on your system, you can `curl -fsSL --header "content-type: text/xml" -d @request.xml http://localhost:8080/ws > output.xml and xmllint --format output.xml`
see the results formatted nicely.

== Summary

Congratulations! You have developed a SOAP-based service with Spring Web Services.
